### PR TITLE
create hookimpl through API instead of importing it

### PR DESCRIPTION
**Pull request by obestwalter**

### CODE REVIEW

**Comment by obestwalter** [comment]
As a side note: I noticed that you use default_factors as part of a hack, not relying on its actual existence. I am also reorganizing the whole constants stuff and adding them to the programmatic API that did not officially exist but was used anyway :) I saw this in pip also. Saying something does not have an API usually just means that people use internals. So better have an API and deal with the pain of having to deprecate things now and then ... see where it is going at https://github.com/Avira/tox/commit/dc62bd638eed871cad3104fe8fec92e39d6e2c94

**Comment by ryanhiebert** [comment]
I think I'd be inclined to take a different view of it. I don't really _care_ that Tox uses pluggy as it's plugin system. It can use whatever it likes, so it feels odd to me that I'd import something from pluggy as my interface to Tox.

**Comment by obestwalter** [comment]
I see. That is actual the first real argument for importing from the host project that I heard ... I will have to think about this and then maybe close a lot of PRs later on - sometimes I go a bit overboard I guess, when I am 100% sure that I am doing the right thing :(

**Comment by obestwalter** [comment]
Closing - importing is the "right" way after all: see https://github.com/pytest-dev/pluggy/issues/130

Thanks @ryanhiebert for letting me see the other perspective :)

**Pull request closed without merging**
