### PR TITLE
Rename toxenv files to envlist

### LINKED ISSUE #80: Rename toxenv
We use the name `toxenv` in several places, because the `TOXENV` environment variable is the mechanism I used to implement the primary feature of Env Detection. When #78 is merged, it will no longer be used, except to make sure we don't do anything if it's already been given. So let's not use it as a name.

Some places that I know it's used:

* [ ] The name of the module that implements env detection. (Rename to `detect` or `envlist`)
* [ ] The name of the function that implements env detection. (Name the same as the module above)
* [ ] The name of the file with the documentation for env detection. (Name the same as those above)
* [ ] The name of the setting for the `[travis:after]` section that says which envs to look for. (Either the same as the above, or perhaps just `env`. Keep the current name for backward compatibility.)

### PR DESCRIPTION
**Pull request by ryanhiebert**
Fixes #80

### CODE REVIEW

**Comment by rpkilby** [comment]
Two thoughts:
-  A part of my says the output should be tested for the warnings, but it seems straightforward enough to not warrant tests.
- Would it make sense to name the files `envlist` instead of `detect`? eg, 
  ```python
  from envlist import detect_envlist
  ```

**Comment by ryanhiebert** [comment]
Yeah, I've got to figure out how to test this section. Right now the after feature is considered "experimental", so I don't have it fully tested (especially the hooks and monkeypatch).

`envlist` was the original plan, as I specified on #80. My main driver for doing something different was #84 , considering how I'd like to spell that flag. I like `--auto-envlist` less than `--detect`, and `--envlist` isn't a clear option IMO. Avoiding multiple words was something that I liked with `--detect`. Perhaps the flag needs to be `--detect-envlist` (or the negative). In that case it would be multiple words, but I'd have no issue renaming the files to `envlist` then.

**Comment by ryanhiebert** [comment]
As I noted on #84, `envlist` is a good name for the feature, so I've updated this PR to use `envlist` as the name that we're renaming toxenv to.

**Comment by ryanhiebert** [comment]
I'm glad that I added tests for the changes in `travis:after`. There were some bugs that needed to be addressed.

**Pull request merged**
