### PR TITLE
Explicit non-support for tox 4

### PR DESCRIPTION
**Pull request by ryanhiebert**
As mentioned in #159 , the simplest way to clean this up is to make the non-support for Tox 4 explicit, that way existing installs shouldn't break.

### CODE REVIEW

**Comment by codeBKashif** [comment]
> I think that I'm stuck. I've got pre-commit happy, but it's not required. The required checks are for Travis and AppVeyor, and those aren't working, presumably the setup in Travis is no longer active. I'll leave this open, but at this point there's really nothing further that I can do without help from others on the tox-dev. Additionally, apart from being willing to add this upper bound version constraint, there's really not much more I'm interested in doing with this repository. I haven't used Travis CI for ages. So I'm not even sure how much anyone else should be interested in getting this library updated, either.

@ryanhiebert With your PR, the tox-travis is working again, that start getting failing after latest release of tox==4.0. Thanks for the effort.

**Review by gaborbernat — APPROVED** [review]

**Comment by ryanhiebert** [comment]
@gaborbernat Thank you for merging! I'm pretty sure the last release was done via auto-upload in Travis. What will it take to release this version?

**Comment by gaborbernat** [comment]
No idea, I'm not maintainer of this package.

**Comment by ryanhiebert** [comment]
OK, thanks. I am, so I'll figure out how to get this released. Thank you for your help getting things unblocked.

**Pull request merged**
